### ISSUE TITLE
Add prototype drawing for "circuit is built from scratch" use case

### ISSUE THREAD

**Issue by Frikster** [Frikster/CircuitSolverApp#17]
Use screenshots if possible
For #16

**Comment by Frikster** [comment]
![image](https://cloud.githubusercontent.com/assets/10172142/20419824/ec3f9a00-ad0d-11e6-82b8-c891b3e49920.png)

Why do yo have a "take picture" and a well take take picture button? And then a "draw a circuit" and a "draw" button?

**Comment by shaefeli** [comment]
That's a good question. For sure, we have to find a more intuitive way on how we want to present the BaseActivity
