### ISSUE TITLE
rewrite the design document section on opencv/tensorflow

### ISSUE THREAD

**Issue by Frikster** [Frikster/CircuitSolverApp#32]
Remove template matching. Talk about tensorflow and opencv methods/algorithms we use

**Comment by npgoossen** [comment]
I have added a bunch of tensorflow information to the design doc. Does anyone wanna take a look at it to verify it isn't awful, and then this issue can be closed.

**Comment by Frikster** [comment]
Read through it and edited the grammar a bit
