### ISSUE TITLE
Swap Voltage Source Use Case

### ISSUE THREAD

**Issue by Frikster** [Frikster/CircuitSolverApp#34]
It has to be possible to click on a voltage source and swap it so that current flows the other way

**Comment by npgoossen** [comment]
we don't have current direction so would it make sense to change voltage polarity?

**Comment by Frikster** [comment]
Not explicitly needed since the user can change a source's direction by erasing and then plotting it again by reversing which side they start and end placing it down with. Not nice, but I don't think we should promise that it'll exist.

All that is really needed is an arrow showing direction for a selected component after solving.
