### ISSUE TITLE
Find out what to do about additional hand in requirements

### ISSUE THREAD

**Issue by jenalam** [Frikster/CircuitSolverApp#52]
According to Milestone 7 description in Course Overview, we need to have a reflection statement and a bunch of other stuff. Doesn't specify any further what should be in these hand-ins...

Milestone 7: Working Product
Submit the following:
- Source code (on Github)
- Installation guide
- User manual (if applicable)
- Final Testing/Validation Document
- Reflection Statements

Course Overview link: 
https://docs.google.com/spreadsheets/d/1QLqi2mmmLFX4Wepw0z-t-CdQOUnrwTyOCubBdb4Rzqc/pubhtml#

**Comment by Frikster** [comment]
@jenalam @npgoossen @LotusFenn @shaefeli @blusz: we need to figure this out and fast.

**Comment by Frikster** [comment]
https://piazza.com/class/iscdbxjilc2du?cid=339

To me this means:
- We need to have nice code to hand in tomorrow
- We need to hand in a Final Testing/Validation Document tomorrow
- We need to hand in a Reflection Statement by Dec. 5
- We can ignore the user manual and installation guide (already in the design docs)
